sudo: required
dist: xenial
language: python
matrix:
  include:
  - os: linux
    python: '3.5'
  - os: linux
    python: '3.6'
  - os: linux
    python: '3.7'
  - os: osx
    language: generic
    env: PYTHON_VERSION=3.7.5
  - os: linux
    python: '3.7'
    env: SNOWFLAKE_AZURE=true
  - os: linux
    python: '3.7'
    env: SNOWFLAKE_GCP=true
install:
- "./scripts/install.sh"
script:
- "./scripts/run_travis.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: "e5OdIjmcrgBi4SOd4u1p5h+Llw55rpbgkQpFHZcJbtyEoO0kTW2WcdqE9SlWkBsLl8zto/XNoJRLjsTF5h8frthbq2p6CO+oiA9Z1XLrfs9uKpfltPcPMULtqI0+diF+bafd48yUTc8mzzC6AyBowGfONT4z43C5kXkQ6PpllYcJ/2cLTwWAEuOQj99PjVbMVStcJKBLaVoo+VAUgdvhofysknmdSZxkNIk6d6cXN68XyfqkblJcwBVa5+Hz/BD9XJuccXpC/kQ6jbGr+SMH4todXkjoDAooxr6Lha9CQ54T4+Ex8zoSHr7Cd9R4a9JSlwKJrmIZLos6tShkAKw9v68NIdz2nR+1eR6wVcVxavOozyFTb532ny4/3HiEeCTyvMIz5paSNyDL0hP+1EJ1gk5I3HKzuc8GqGGn9Kcb5EcSQ+rHPYW9lLPopCQtvfx5cBaEyAPqFOaHbz0N1+d6LKM+uemeWpRZW5LnbMg3yPYjYOa8UBFgYRgSHYkNZ9/QWYMD9TydjjpOGY4UjOG/G8fHXz7dNObQiA8/qlY8EKxeol7lhkxAgxMerFmP7r4DEJqjbaazQ7IvMwkjNKGKtDKpO0DHhV4q/8O4hyaeXdDFvzrTOBidzM3bRlvY8xUJPPOiIkZKNtPkSX6WucjGv86YTbHV2QepRd7+qQNH7I4="
